// Users
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILURE = "LOAD_USERS_FAILURE";

// Squads
export const ADD_SQUAD = "ADD_SQUAD";
export const REMOVE_SQUAD = "REMOVE_SQUAD";
export const UPDATE_SQUAD = "UPDATE_SQUAD";

export const LOAD_SQUADS_START = "LOAD_SQUADS_START";
export const LOAD_SQUADS_SUCCESS = "LOAD_SQUADS_SUCCESS";
export const LOAD_SQUADS_FAILURE = "LOAD_SQUADS_FAILURE";

// Releases
export const ADD_RELEASE = "ADD_RELEASE";
export const REMOVE_RELEASE = "REMOVE_RELEASE";
export const UPDATE_RELEASE = "UPDATE_RELEASE";

export const LOAD_RELEASES_START = "LOAD_RELEASES_START";
export const LOAD_RELEASES_SUCCESS = "LOAD_RELEASES_SUCCESS";
export const LOAD_RELEASES_FAILURE = "LOAD_RELEASES_FAILURE";

// Sprints
export const ADD_SPRINT = "ADD_SPRINT";
export const REMOVE_SPRINT = "REMOVE_SPRINT";
export const UPDATE_SPRINT = "UPDATE_SPRINT";

export const LOAD_SPRINTS_START = "LOAD_SPRINTS_START";
export const LOAD_SPRINTS_SUCCESS = "LOAD_SPRINTS_SUCCESS";
export const LOAD_SPRINTS_FAILURE = "LOAD_SPRINTS_FAILURE";
