// Users
export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const REMOVE_USER = "REMOVE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILURE = "LOAD_USERS_FAILURE";

// Squads
export const ADD_SQUAD_START = "ADD_SQUAD_START";
export const ADD_SQUAD_SUCCESS = "ADD_SQUAD_SUCCESS";
export const ADD_SQUAD_FAILURE = "ADD_SQUAD_FAILURE";

export const REMOVE_SQUAD = "REMOVE_SQUAD";
export const UPDATE_SQUAD = "UPDATE_SQUAD";

export const LOAD_SQUADS_START = "LOAD_SQUADS_START";
export const LOAD_SQUADS_SUCCESS = "LOAD_SQUADS_SUCCESS";
export const LOAD_SQUADS_FAILURE = "LOAD_SQUADS_FAILURE";

// Releases
export const ADD_RELEASE_START = "ADD_RELEASE_START";
export const ADD_RELEASE_SUCCESS = "ADD_RELEASE_SUCCESS";
export const ADD_RELEASE_FAILURE = "ADD_RELEASE_FAILURE";

export const REMOVE_RELEASE = "REMOVE_RELEASE";
export const UPDATE_RELEASE = "UPDATE_RELEASE";

export const LOAD_RELEASES_START = "LOAD_RELEASES_START";
export const LOAD_RELEASES_SUCCESS = "LOAD_RELEASES_SUCCESS";
export const LOAD_RELEASES_FAILURE = "LOAD_RELEASES_FAILURE";

// Sprints
export const ADD_SPRINT_START = "ADD_SPRINT_START";
export const ADD_SPRINT_SUCCESS = "ADD_SPRINT_SUCCESS";
export const ADD_SPRINT_FAILURE = "ADD_SPRINT_FAILURE";

export const REMOVE_SPRINT = "REMOVE_SPRINT";
export const UPDATE_SPRINT = "UPDATE_SPRINT";

export const LOAD_SPRINTS_START = "LOAD_SPRINTS_START";
export const LOAD_SPRINTS_SUCCESS = "LOAD_SPRINTS_SUCCESS";
export const LOAD_SPRINTS_FAILURE = "LOAD_SPRINTS_FAILURE";

// Retro Board
export const LOAD_RETROS_START = "LOAD_RETROS_START";
export const LOAD_RETROS_SUCCESS = "LOAD_RETROS_SUCCESS";
export const LOAD_RETROS_FAILURE = "LOAD_RETROS_FAILURE";

export const ADD_RETRO_START = "ADD_RETRO_START";
export const ADD_RETRO_SUCCESS = "ADD_RETRO_SUCCESS";
export const ADD_RETRO_FAILURE = "ADD_RETRO_FAILURE";

// Squads, Releases, Sprints associated with current user
export const LOAD_CURRENTUSERSQUADS_START = "LOAD_CURRENTUSERSQUADS_START";
export const LOAD_CURRENTUSERSQUADS_SUCCESS = "LOAD_CURRENTUSERSQUADS_SUCCESS";
export const LOAD_CURRENTUSERSQUADS_FAILURE = "LOAD_CURRENTUSERSQUADS_FAILURE";

export const LOAD_CURRENTUSERRELEASES_START = "LOAD_CURRENTUSERRELEASES_START";
export const LOAD_CURRENTUSERRELEASES_SUCCESS =
  "LOAD_CURRENTUSERRELEASES_SUCCESS";
export const LOAD_CURRENTUSERRELEASES_FAILURE =
  "LOAD_CURRENTUSERRELEASES_FAILURE";

export const LOAD_CURRENTUSERSPRINTS_START = "LOAD_CURRENTUSERSPRINTS_START";
export const LOAD_CURRENTUSERSPRINTS_SUCCESS =
  "LOAD_CURRENTUSERSPRINTS_SUCCESS";
export const LOAD_CURRENTUSERSPRINTS_FAILURE =
  "LOAD_CURRENTUSERSPRINTS_FAILURE";

// get current user
export const LOAD_CURRENTUSER_START = "LOAD_CURRENTUSER_START";
export const LOAD_CURRENTUSER_SUCCESS = "LOAD_CURRENTUSER_SUCCESS";
export const LOAD_CURRENTUSER_FAILURE = "LOAD_CURRENTUSER_FAILURE";

export const CLEAR_CURRENTUSER = "CLEAR_CURRENTUSER";
