apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: bapana.xyz
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-service
              servicePort: 3000
          - path: /api/squads/?(.*)
            backend:
              serviceName: squad-service
              servicePort: 3000
          - path: /api/releases/?(.*)
            backend:
              serviceName: release-service
              servicePort: 3000
          - path: /api/sprints/?(.*)
            backend:
              serviceName: sprint-service
              servicePort: 3000
          - path: /api/retros/?(.*)
            backend:
              serviceName: retro-service
              servicePort: 3000
          - path: /api/leaves/?(.*)
            backend:
              serviceName: capacity-service
              servicePort: 3000
          - path: /api/estimation/?(.*)
            backend:
              serviceName: estimation-service
              servicePort: 3000
          - path: /socket.io/?(.*)
            backend:
              serviceName: planner-service
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-service
              servicePort: 3000
