apiVersion: apps/v1
kind: Deployment
metadata:
    name: sprint-mongo-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sprint-mongo
    template:
        metadata:
            labels:
                app: sprint-mongo
        spec:
            containers:
                - name: sprint-mongo
                  image: mongo
---
apiVersion: v1
kind: Service
metadata:
    name: sprint-mongo-service
spec:
    selector:
        app: sprint-mongo
    ports:
        - name: db
          protocol: TCP
          port: 27017
          targetPort: 27017