apiVersion: apps/v1
kind: Deployment
metadata:
    name: squad-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: squad
    template:
        metadata:
            labels:
                app: squad
        spec:
            containers:
                - name: squad
                  image: parthikrb/squad
                  env:
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: NATS_URL
                        value: 'http://nats-service:4222'
                      - name: NATS_CLUSTER_ID
                        value: esteamate
                      - name: MONGO_URI
                        value: 'mongodb://host.docker.internal:27017/squad'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
    name: squad-service
spec:
    selector:
        app: squad
    ports:
        - name: squad
          protocol: TCP
          port: 3000
          targetPort: 3000
